version: "3"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  web:
    build: dash_app/
    command: python3 app.py
    depends_on:
      - es
    ports:
      - 8050:8050
    volumes:
      - ./dash_app:/usr/src/app